COMPILE	=	g++ -Wall -Werror -Wextra -o

all:
	$(COMPILE) my_cat my_cat.cpp
	$(COMPILE) my_convert_temp my_convert_temp.cpp
	$(COMPILE) test KoalaNurse.cpp SickKoala.cpp KoalaDoctor.cpp

clean:
	rm -f my_cat my_convert_temp test

fclean: clean

re: fclean all

